# Generated by Django 4.2.3 on 2023-07-12 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pastebin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('expiration', models.IntegerField(choices=[(0, 'one hour'), (1, 'one day'), (2, 'one week'), (3, 'one month'), (4, 'forever')], default=0)),
                ('public', models.BooleanField(default=True)),
                ('polycount', models.IntegerField(blank=True, default=0)),
                ('width', models.FloatField(blank=True, default=0)),
                ('depth', models.FloatField(blank=True, default=0)),
                ('height', models.FloatField(blank=True, default=0)),
                ('file', models.FileField(upload_to=pastebin.models.model_path)),
                ('sourcefile', models.FileField(blank=True, upload_to=pastebin.models.source_path)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
